spring:
    jpa:
        database: MySQL
        hibernate:
            ddl-auto: update
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate.show_sql: true
          hibernate.format_sql: true

    datasource:
        url: jdbc:mysql://google/mpush?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=mpush-202719:europe-west1:mpush-database-m
        username: mpush
        password: Mpush2017*
        driver-class-name: com.mysql.jdbc.Driver