spring:
    jpa:
        database: MySQL
        hibernate:
            ddl-auto: update
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate.show_sql: true
          hibernate.format_sql: true

    datasource:
        url: jdbc:mysql://mysql-doura.alwaysdata.net:3306/doura_mpush
        username: doura_mpush
        password: Mpush2017*
        driver-class-name: com.mysql.jdbc.Driver